### ISSUE TITLE
Function parameters

### ISSUE THREAD

**Issue by SimardeepKaur** [UBC-MDS/hueniverrrsity#12]
Since all the functions are similar, we'll have to decide on the same parameters and returns. If any of you has already done that. Please comment

**Comment by reikookamoto** [comment]
We could pass `fill` or `color`. Passing `fill` could call `scale_fill_manual(values = <color_palette_name>)` and passing `color` could call `scale_color_manual(values = <color_palette_name>)`.  Basically, `scale_fill_manual()` works for box plots, bar plots, and violion plots while `scale_color_manual()` works for lines and points. 

https://www.datanovia.com/en/blog/ggplot-colors-best-tricks-you-will-love/#set-custom-color-palettes

**Comment by SimardeepKaur** [comment]
Also, since we'll just be adding the colors in the function and different universities will have different functions , so having a function like "theme_ubc()" would also work. 
Let me know, if I am missing something here.

**Comment by reikookamoto** [comment]
I'm thinking that in the definition of `theme_ubc()` we can have `scale_fill_manual()` and `scale_color_manual()`. Then the function could be called via `theme_ubc(style='fill')` or`theme_ubc(style='color')`. So the parameter of `theme_ubc()` will only be `style`. Did that clear things up?
